# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cleure/Development/Projects/C-hashtable

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cleure/Development/Projects/C-hashtable

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cleure/Development/Projects/C-hashtable/CMakeFiles /Users/cleure/Development/Projects/C-hashtable/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cleure/Development/Projects/C-hashtable/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named htable

# Build rule for target.
htable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 htable
.PHONY : htable

# fast build rule for target.
htable/fast:
	$(MAKE) -f CMakeFiles/htable.dir/build.make CMakeFiles/htable.dir/build
.PHONY : htable/fast

#=============================================================================
# Target rules for targets named tests/bin/test-01-new

# Build rule for target.
tests/bin/test-01-new: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/bin/test-01-new
.PHONY : tests/bin/test-01-new

# fast build rule for target.
tests/bin/test-01-new/fast:
	$(MAKE) -f CMakeFiles/tests/bin/test-01-new.dir/build.make CMakeFiles/tests/bin/test-01-new.dir/build
.PHONY : tests/bin/test-01-new/fast

#=============================================================================
# Target rules for targets named tests/bin/test-02-add

# Build rule for target.
tests/bin/test-02-add: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/bin/test-02-add
.PHONY : tests/bin/test-02-add

# fast build rule for target.
tests/bin/test-02-add/fast:
	$(MAKE) -f CMakeFiles/tests/bin/test-02-add.dir/build.make CMakeFiles/tests/bin/test-02-add.dir/build
.PHONY : tests/bin/test-02-add/fast

#=============================================================================
# Target rules for targets named tests/bin/test-03-clone

# Build rule for target.
tests/bin/test-03-clone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/bin/test-03-clone
.PHONY : tests/bin/test-03-clone

# fast build rule for target.
tests/bin/test-03-clone/fast:
	$(MAKE) -f CMakeFiles/tests/bin/test-03-clone.dir/build.make CMakeFiles/tests/bin/test-03-clone.dir/build
.PHONY : tests/bin/test-03-clone/fast

#=============================================================================
# Target rules for targets named tests/bin/test-04-resize

# Build rule for target.
tests/bin/test-04-resize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/bin/test-04-resize
.PHONY : tests/bin/test-04-resize

# fast build rule for target.
tests/bin/test-04-resize/fast:
	$(MAKE) -f CMakeFiles/tests/bin/test-04-resize.dir/build.make CMakeFiles/tests/bin/test-04-resize.dir/build
.PHONY : tests/bin/test-04-resize/fast

#=============================================================================
# Target rules for targets named tests/bin/test-05-update

# Build rule for target.
tests/bin/test-05-update: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/bin/test-05-update
.PHONY : tests/bin/test-05-update

# fast build rule for target.
tests/bin/test-05-update/fast:
	$(MAKE) -f CMakeFiles/tests/bin/test-05-update.dir/build.make CMakeFiles/tests/bin/test-05-update.dir/build
.PHONY : tests/bin/test-05-update/fast

#=============================================================================
# Target rules for targets named tests/bin/test-06-remove

# Build rule for target.
tests/bin/test-06-remove: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests/bin/test-06-remove
.PHONY : tests/bin/test-06-remove

# fast build rule for target.
tests/bin/test-06-remove/fast:
	$(MAKE) -f CMakeFiles/tests/bin/test-06-remove.dir/build.make CMakeFiles/tests/bin/test-06-remove.dir/build
.PHONY : tests/bin/test-06-remove/fast

src/MurmurHash3.o: src/MurmurHash3.c.o
.PHONY : src/MurmurHash3.o

# target to build an object file
src/MurmurHash3.c.o:
	$(MAKE) -f CMakeFiles/htable.dir/build.make CMakeFiles/htable.dir/src/MurmurHash3.c.o
.PHONY : src/MurmurHash3.c.o

src/MurmurHash3.i: src/MurmurHash3.c.i
.PHONY : src/MurmurHash3.i

# target to preprocess a source file
src/MurmurHash3.c.i:
	$(MAKE) -f CMakeFiles/htable.dir/build.make CMakeFiles/htable.dir/src/MurmurHash3.c.i
.PHONY : src/MurmurHash3.c.i

src/MurmurHash3.s: src/MurmurHash3.c.s
.PHONY : src/MurmurHash3.s

# target to generate assembly for a file
src/MurmurHash3.c.s:
	$(MAKE) -f CMakeFiles/htable.dir/build.make CMakeFiles/htable.dir/src/MurmurHash3.c.s
.PHONY : src/MurmurHash3.c.s

src/hashtable.o: src/hashtable.c.o
.PHONY : src/hashtable.o

# target to build an object file
src/hashtable.c.o:
	$(MAKE) -f CMakeFiles/htable.dir/build.make CMakeFiles/htable.dir/src/hashtable.c.o
.PHONY : src/hashtable.c.o

src/hashtable.i: src/hashtable.c.i
.PHONY : src/hashtable.i

# target to preprocess a source file
src/hashtable.c.i:
	$(MAKE) -f CMakeFiles/htable.dir/build.make CMakeFiles/htable.dir/src/hashtable.c.i
.PHONY : src/hashtable.c.i

src/hashtable.s: src/hashtable.c.s
.PHONY : src/hashtable.s

# target to generate assembly for a file
src/hashtable.c.s:
	$(MAKE) -f CMakeFiles/htable.dir/build.make CMakeFiles/htable.dir/src/hashtable.c.s
.PHONY : src/hashtable.c.s

tests/test-01-new.o: tests/test-01-new.c.o
.PHONY : tests/test-01-new.o

# target to build an object file
tests/test-01-new.c.o:
	$(MAKE) -f CMakeFiles/tests/bin/test-01-new.dir/build.make CMakeFiles/tests/bin/test-01-new.dir/tests/test-01-new.c.o
.PHONY : tests/test-01-new.c.o

tests/test-01-new.i: tests/test-01-new.c.i
.PHONY : tests/test-01-new.i

# target to preprocess a source file
tests/test-01-new.c.i:
	$(MAKE) -f CMakeFiles/tests/bin/test-01-new.dir/build.make CMakeFiles/tests/bin/test-01-new.dir/tests/test-01-new.c.i
.PHONY : tests/test-01-new.c.i

tests/test-01-new.s: tests/test-01-new.c.s
.PHONY : tests/test-01-new.s

# target to generate assembly for a file
tests/test-01-new.c.s:
	$(MAKE) -f CMakeFiles/tests/bin/test-01-new.dir/build.make CMakeFiles/tests/bin/test-01-new.dir/tests/test-01-new.c.s
.PHONY : tests/test-01-new.c.s

tests/test-02-add.o: tests/test-02-add.c.o
.PHONY : tests/test-02-add.o

# target to build an object file
tests/test-02-add.c.o:
	$(MAKE) -f CMakeFiles/tests/bin/test-02-add.dir/build.make CMakeFiles/tests/bin/test-02-add.dir/tests/test-02-add.c.o
.PHONY : tests/test-02-add.c.o

tests/test-02-add.i: tests/test-02-add.c.i
.PHONY : tests/test-02-add.i

# target to preprocess a source file
tests/test-02-add.c.i:
	$(MAKE) -f CMakeFiles/tests/bin/test-02-add.dir/build.make CMakeFiles/tests/bin/test-02-add.dir/tests/test-02-add.c.i
.PHONY : tests/test-02-add.c.i

tests/test-02-add.s: tests/test-02-add.c.s
.PHONY : tests/test-02-add.s

# target to generate assembly for a file
tests/test-02-add.c.s:
	$(MAKE) -f CMakeFiles/tests/bin/test-02-add.dir/build.make CMakeFiles/tests/bin/test-02-add.dir/tests/test-02-add.c.s
.PHONY : tests/test-02-add.c.s

tests/test-03-clone.o: tests/test-03-clone.c.o
.PHONY : tests/test-03-clone.o

# target to build an object file
tests/test-03-clone.c.o:
	$(MAKE) -f CMakeFiles/tests/bin/test-03-clone.dir/build.make CMakeFiles/tests/bin/test-03-clone.dir/tests/test-03-clone.c.o
.PHONY : tests/test-03-clone.c.o

tests/test-03-clone.i: tests/test-03-clone.c.i
.PHONY : tests/test-03-clone.i

# target to preprocess a source file
tests/test-03-clone.c.i:
	$(MAKE) -f CMakeFiles/tests/bin/test-03-clone.dir/build.make CMakeFiles/tests/bin/test-03-clone.dir/tests/test-03-clone.c.i
.PHONY : tests/test-03-clone.c.i

tests/test-03-clone.s: tests/test-03-clone.c.s
.PHONY : tests/test-03-clone.s

# target to generate assembly for a file
tests/test-03-clone.c.s:
	$(MAKE) -f CMakeFiles/tests/bin/test-03-clone.dir/build.make CMakeFiles/tests/bin/test-03-clone.dir/tests/test-03-clone.c.s
.PHONY : tests/test-03-clone.c.s

tests/test-04-resize.o: tests/test-04-resize.c.o
.PHONY : tests/test-04-resize.o

# target to build an object file
tests/test-04-resize.c.o:
	$(MAKE) -f CMakeFiles/tests/bin/test-04-resize.dir/build.make CMakeFiles/tests/bin/test-04-resize.dir/tests/test-04-resize.c.o
.PHONY : tests/test-04-resize.c.o

tests/test-04-resize.i: tests/test-04-resize.c.i
.PHONY : tests/test-04-resize.i

# target to preprocess a source file
tests/test-04-resize.c.i:
	$(MAKE) -f CMakeFiles/tests/bin/test-04-resize.dir/build.make CMakeFiles/tests/bin/test-04-resize.dir/tests/test-04-resize.c.i
.PHONY : tests/test-04-resize.c.i

tests/test-04-resize.s: tests/test-04-resize.c.s
.PHONY : tests/test-04-resize.s

# target to generate assembly for a file
tests/test-04-resize.c.s:
	$(MAKE) -f CMakeFiles/tests/bin/test-04-resize.dir/build.make CMakeFiles/tests/bin/test-04-resize.dir/tests/test-04-resize.c.s
.PHONY : tests/test-04-resize.c.s

tests/test-05-update.o: tests/test-05-update.c.o
.PHONY : tests/test-05-update.o

# target to build an object file
tests/test-05-update.c.o:
	$(MAKE) -f CMakeFiles/tests/bin/test-05-update.dir/build.make CMakeFiles/tests/bin/test-05-update.dir/tests/test-05-update.c.o
.PHONY : tests/test-05-update.c.o

tests/test-05-update.i: tests/test-05-update.c.i
.PHONY : tests/test-05-update.i

# target to preprocess a source file
tests/test-05-update.c.i:
	$(MAKE) -f CMakeFiles/tests/bin/test-05-update.dir/build.make CMakeFiles/tests/bin/test-05-update.dir/tests/test-05-update.c.i
.PHONY : tests/test-05-update.c.i

tests/test-05-update.s: tests/test-05-update.c.s
.PHONY : tests/test-05-update.s

# target to generate assembly for a file
tests/test-05-update.c.s:
	$(MAKE) -f CMakeFiles/tests/bin/test-05-update.dir/build.make CMakeFiles/tests/bin/test-05-update.dir/tests/test-05-update.c.s
.PHONY : tests/test-05-update.c.s

tests/test-06-remove.o: tests/test-06-remove.c.o
.PHONY : tests/test-06-remove.o

# target to build an object file
tests/test-06-remove.c.o:
	$(MAKE) -f CMakeFiles/tests/bin/test-06-remove.dir/build.make CMakeFiles/tests/bin/test-06-remove.dir/tests/test-06-remove.c.o
.PHONY : tests/test-06-remove.c.o

tests/test-06-remove.i: tests/test-06-remove.c.i
.PHONY : tests/test-06-remove.i

# target to preprocess a source file
tests/test-06-remove.c.i:
	$(MAKE) -f CMakeFiles/tests/bin/test-06-remove.dir/build.make CMakeFiles/tests/bin/test-06-remove.dir/tests/test-06-remove.c.i
.PHONY : tests/test-06-remove.c.i

tests/test-06-remove.s: tests/test-06-remove.c.s
.PHONY : tests/test-06-remove.s

# target to generate assembly for a file
tests/test-06-remove.c.s:
	$(MAKE) -f CMakeFiles/tests/bin/test-06-remove.dir/build.make CMakeFiles/tests/bin/test-06-remove.dir/tests/test-06-remove.c.s
.PHONY : tests/test-06-remove.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... htable"
	@echo "... rebuild_cache"
	@echo "... tests/bin/test-01-new"
	@echo "... tests/bin/test-02-add"
	@echo "... tests/bin/test-03-clone"
	@echo "... tests/bin/test-04-resize"
	@echo "... tests/bin/test-05-update"
	@echo "... tests/bin/test-06-remove"
	@echo "... src/MurmurHash3.o"
	@echo "... src/MurmurHash3.i"
	@echo "... src/MurmurHash3.s"
	@echo "... src/hashtable.o"
	@echo "... src/hashtable.i"
	@echo "... src/hashtable.s"
	@echo "... tests/test-01-new.o"
	@echo "... tests/test-01-new.i"
	@echo "... tests/test-01-new.s"
	@echo "... tests/test-02-add.o"
	@echo "... tests/test-02-add.i"
	@echo "... tests/test-02-add.s"
	@echo "... tests/test-03-clone.o"
	@echo "... tests/test-03-clone.i"
	@echo "... tests/test-03-clone.s"
	@echo "... tests/test-04-resize.o"
	@echo "... tests/test-04-resize.i"
	@echo "... tests/test-04-resize.s"
	@echo "... tests/test-05-update.o"
	@echo "... tests/test-05-update.i"
	@echo "... tests/test-05-update.s"
	@echo "... tests/test-06-remove.o"
	@echo "... tests/test-06-remove.i"
	@echo "... tests/test-06-remove.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

